/* Real browser regression: isolated local test data only. No production data. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),crypto=require('crypto');
const {chromium}=require('playwright');const bwip=require('bwip-js');
const root=path.resolve(__dirname,'..'),out=process.env.SCOPE_QA_OUT||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const results=[];async function check(name,fn){try{await fn();results.push({name,result:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,result:'FAIL',detail:e.message});console.log('FAIL '+name+' '+e.message)}}
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name.endsWith('/'))name+='index.html';try{res.setHeader('Content-Type',mime[path.extname(name)]||'application/octet-stream');res.end(fs.readFileSync(path.join(root,name)))}catch{res.statusCode=404;res.end('Not found')}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({executablePath:process.env.SCOPE_CHROMIUM||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['camera'],acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await check('Application loads with actual decoder and persistent IndexedDB',async()=>{await page.goto(base+'/');await page.waitForFunction(()=>document.getElementById('offlineBadge').textContent!=='Ready');assert.equal(await page.evaluate(()=>typeof Html5Qrcode),'function');assert.equal(await page.locator('#batchCount').textContent(),'0')});
 await check('390px / 375px / 320px layout: no horizontal overflow, centered emblem, 44px buttons',async()=>{for(const width of [390,375,320]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const a=await page.locator('.brand-badge').boundingBox(),b=await page.locator('.brand-logo').boundingBox();assert.ok(Math.abs(a.x+a.width/2-b.x-b.width/2)<1);assert.ok(Math.abs(a.y+a.height/2-b.y-b.height/2)<1);for(const btn of await page.locator('button:visible').all()){const r=await btn.boundingBox();assert.ok(r.height>=44,'Small tap target')}}await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile-capture.png'),fullPage:false})});
 await check('Empty receipt rejected without adding a record',async()=>{await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('scanStatus').textContent.includes('identifier'));assert.equal(await page.locator('#batchCount').textContent(),'0')});
 const raw='SDN M1234567890123 | TCN TEST-TCN-001 | NIIN 012345678';
 await check('Manual label extraction and all receipt fields saved',async()=>{await page.locator('#barcodeRaw').fill(raw);await page.locator('#sdn').focus();assert.equal(await page.locator('#sdn').inputValue(),'M1234567890123');assert.equal(await page.locator('#tcn').inputValue(),'TEST-TCN-001');assert.equal(await page.locator('#niin').inputValue(),'012345678');await page.locator('#qty').fill('7');await page.locator('#condition').fill('a');await page.locator('#packages').fill('2');await page.locator('#notes').fill('QA fixture: carton damage');await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('batchCount').textContent==='1');const r=(await page.evaluate(()=>getAll()))[0];assert.equal(r.qtyReceived,7);assert.equal(r.conditionCode,'A');assert.equal(r.packageCount,2);assert.equal(r.notes,'QA fixture: carton damage');assert.equal(r.matchStatus,'AWAITING_DASF_MATCH')});
 await check('Drafts survive reload and edit preserves one record',async()=>{await page.reload();await page.waitForFunction(()=>document.getElementById('batchCount').textContent==='1');await page.locator('[data-action=edit]').click();await page.waitForFunction(()=>document.getElementById('saveBtn').textContent==='Update Draft');assert.equal(await page.locator('#notes').inputValue(),'QA fixture: carton damage');await page.locator('#qty').fill('9');await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('saveBtn').textContent==='Add to Batch');const r=await page.evaluate(()=>getAll());assert.equal(r.length,1);assert.equal(r[0].qtyReceived,9);assert.ok(r[0].createdAt)});
 await check('Duplicate SDN warns; cancel leaves batch unchanged',async()=>{await page.locator('#sdn').fill('M1234567890123');let message='';page.once('dialog',async d=>{message=d.message();await d.dismiss()});await page.locator('#saveBtn').click();await page.waitForTimeout(100);assert.match(message,/duplicate/);assert.equal((await page.evaluate(()=>getAll())).length,1);await page.locator('#clearBtn').click()});
 await check('Actual photo decoder reads synthetic Code 128 label',async()=>{const png=await bwip.toBuffer({bcid:'code128',text:'M9876543210123',scale:4,height:20,padding:20});await page.locator('#photoScanInput').setInputFiles({name:'qa-barcode.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>document.getElementById('barcodeRaw').value==='M9876543210123',{},{timeout:15000});await page.locator('#clearBtn').click()});
 await check('Camera scanner starts and stops using synthetic camera stream',async()=>{await page.locator('#scanBtn').click();await page.waitForFunction(()=>document.getElementById('scanStatus').textContent.startsWith('Camera ready'),{},{timeout:15000});assert.ok(await page.locator('#cameraWrap').isVisible());await page.screenshot({path:path.join(out,'mobile-scanner.png')});await page.locator('#stopScanBtn').click();assert.ok(await page.locator('#cameraWrap').isHidden())});
 await check('JSON dialog shows package hash and required DASF status',async()=>{await page.locator('#previewBtn').click();await page.locator('#jsonDialog').waitFor({state:'visible'});const obj=JSON.parse(await page.locator('#jsonPreview').textContent());assert.equal(obj.recordCount,1);assert.equal(obj.sourceAppVersion,'0.3.0');assert.equal(obj.records[0].matchStatus,'AWAITING_DASF_MATCH');assert.equal(obj.recordsSha256,crypto.createHash('sha256').update(JSON.stringify(obj.records)).digest('hex'));await page.screenshot({path:path.join(out,'mobile-json.png')});await page.locator('#closeJsonBtn').click();assert.ok(await page.locator('#jsonDialog').isHidden())});
 await check('Export downloads a complete .scopepkg with all preserved fields',async()=>{const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#exportBtn').click()]);assert.ok(d.suggestedFilename().endsWith('.scopepkg'));const f=await d.path();const p=JSON.parse(fs.readFileSync(f));assert.equal(p.recordCount,1);assert.equal(p.records[0].qtyReceived,9);assert.equal(p.records[0].packageCount,2);assert.equal(p.records[0].notes,'QA fixture: carton damage')});
 await check('Offline reload retains drafts and locally cached barcode decoder',async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.getElementById('offlineBadge').textContent==='Offline');assert.equal(await page.locator('#batchCount').textContent(),'1');assert.equal(await page.evaluate(()=>typeof Html5Qrcode),'function');await page.screenshot({path:path.join(out,'mobile-offline.png')});await context.setOffline(false)});
 await check('Batch cards and handoff stay readable at narrow widths',async()=>{await page.locator('#batch').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'mobile-batch.png')});for(const width of [320,375,390]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile-full.png'),fullPage:true})});
 await check('Reduced-motion disables hover transitions',async()=>{await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#scanBtn').evaluate(e=>getComputedStyle(e).transitionDuration),'0s')});
 await check('Delete and clear batch preserve confirmation controls',async()=>{page.once('dialog',d=>d.accept());await page.locator('[data-action=delete]').click();await page.waitForFunction(()=>document.getElementById('batchCount').textContent==='0');await page.locator('#sdn').fill('TEST-SECOND');await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('batchCount').textContent==='1');page.once('dialog',d=>d.accept());await page.locator('#newBatchBtn').click();await page.waitForFunction(()=>document.getElementById('batchCount').textContent==='0')});
 await check('No uncaught browser errors',async()=>assert.deepEqual(errors,[]));
 await browser.close();server.close();fs.writeFileSync(path.join(out,'mobile-results.json'),JSON.stringify(results,null,2));console.log(results.map(r=>r.result+' '+r.name+(r.detail?' — '+r.detail:'')).join('\n'));if(results.some(r=>r.result==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exit(1)});
